import type { NextPage } from 'next';
import Head from 'next/head';
import { Banner } from '../components/Banner';
import { Carousel } from '../components/Carousel';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { Products } from '../components/Products';

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-black ">
      <Head>
        <title>Basement | Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Carousel />
      <Products />
      <Footer />
    </div>
  );
};

export default Home;
